class QuantumPortfolioError(Exception): ...
class DataValidationError(QuantumPortfolioError): ...
class OptimizationError(QuantumPortfolioError): ...
class ConfigurationError(QuantumPortfolioError): ...
class SolverUnavailableError(OptimizationError): ...
